"""Portal user authentication routes — invite-only email + password + hCaptcha.

Human lane (this module) complements the machine lane (tenant API keys in
``backend/auth.py``). Signup requires a single-use, time-bounded invite
generated by a tenant admin (``POST /api/auth/invites``); there is no public
self-serve account creation — a clinical platform does not get an open
registration endpoint.

Security posture:
  * hCaptcha is verified *before* any credential work and fails closed.
  * Login never reveals whether an email exists: uniform error, dummy
    Argon2 verify on the not-found path (see ``core/user_auth``).
  * Five consecutive failures lock the account for 15 minutes.
  * Refresh tokens rotate; presenting a revoked token revokes the whole
    family (theft detection, RFC 6819 §5.2.2.3).
  * Every auth event lands in the hash-chained audit log. Passwords and
    tokens are never logged.
"""

from __future__ import annotations

import logging
import uuid
from datetime import datetime, timedelta, timezone
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, Request, status
from pydantic import BaseModel
from sqlalchemy.exc import IntegrityError, SQLAlchemyError
from sqlalchemy.orm import Session

from backend.auth import (
    AuthenticatedClient,
    hash_password,
    require_api_client,
    require_scope,
    verify_password_hash,
)
from core import models
from core.captcha import verify_captcha
from core.config import settings
from core.db_session import auth_flow_session, tenant_scoped_session
from core.user_auth import (
    KNOWN_ROLES,
    LOCKOUT_MINUTES,
    MAX_FAILED_LOGINS,
    dummy_password_verify,
    generate_invite_token,
    generate_refresh_token,
    invite_token_digest,
    issue_access_token,
    normalize_email,
    refresh_token_digest,
    validate_password,
)

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/auth", tags=["portal-auth"])

_INVALID_CREDENTIALS = "Invalid email or password."
_INVALID_INVITE = "That invite link is invalid or has expired."


def _audit(db: Session, event_type: str, payload: dict, *, tenant_id, request: Request) -> None:
    """Late-import the audit logger to avoid a circular import with
    ``backend/api.py`` (which includes this router at app-build time)."""

    try:
        from backend.api import log_audit_event_postgres

        log_audit_event_postgres(
            db,
            event_type=event_type,
            payload_data=payload,
            tenant_id=str(tenant_id) if tenant_id else None,
            request_id=getattr(request.state, "request_id", None),
        )
    except Exception as exc:  # audit must not break the auth flow
        logger.warning("auth audit log failed for %s: %s", event_type, exc)


def _client_ip(request: Request) -> Optional[str]:
    return request.client.host if request.client else None


def _issue_session(
    db: Session,
    *,
    user: models.User,
    request: Request,
    family_id: Optional[uuid.UUID] = None,
) -> dict:
    """Create a refresh-token row + access JWT for ``user``."""

    refresh_token = generate_refresh_token()
    family = family_id or uuid.uuid4()
    row = models.AuthRefreshToken(
        user_id=user.id,
        tenant_id=user.tenant_id,
        token_hash=refresh_token_digest(refresh_token),
        family_id=family,
        expires_at=datetime.now(timezone.utc)
        + timedelta(days=settings.BUDDI_JWT_REFRESH_DAYS),
        created_ip=_client_ip(request),
        user_agent=(request.headers.get("user-agent") or "")[:255] or None,
    )
    db.add(row)
    access_token, expires_in = issue_access_token(
        user_id=user.id,
        tenant_id=user.tenant_id,
        role=user.role,
        session_id=family,
    )
    return {
        "access_token": access_token,
        "token_type": "bearer",
        "expires_in": expires_in,
        "refresh_token": refresh_token,
        "user": {
            "id": str(user.id),
            "email": user.email,
            "full_name": user.full_name,
            "role": user.role,
            "tenant_id": str(user.tenant_id),
        },
    }


class SignupRequest(BaseModel):
    invite_token: str
    email: str
    password: str
    full_name: Optional[str] = None
    captcha_token: Optional[str] = None


class LoginRequest(BaseModel):
    email: str
    password: str
    captcha_token: Optional[str] = None


class RefreshRequest(BaseModel):
    refresh_token: str


class LogoutRequest(BaseModel):
    refresh_token: str


class InviteRequest(BaseModel):
    email: Optional[str] = None
    role: str = "clinician"


def _require_captcha(token: Optional[str], request: Request) -> None:
    if not verify_captcha(token, remote_ip=_client_ip(request)):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Captcha verification failed — please try again.",
        )


def _check_email_shape(email: str) -> None:
    local, sep, domain = (email or "").partition("@")
    if not sep or not local or "." not in domain:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail="A valid email address is required.",
        )



@router.post("/signup", status_code=status.HTTP_201_CREATED)
def signup(body: SignupRequest, request: Request, auth_ctx=Depends(auth_flow_session)):
    """Redeem an invite: create the account and return a live session."""

    db, stamper = auth_ctx
    _require_captcha(body.captcha_token, request)
    _check_email_shape(body.email)
    password_error = validate_password(body.password)
    if password_error:
        raise HTTPException(status_code=status.HTTP_422_UNPROCESSABLE_ENTITY, detail=password_error)

    email = normalize_email(body.email)
    now = datetime.now(timezone.utc)
    invite = (
        db.query(models.TenantInvite)
        .filter(models.TenantInvite.token_hash == invite_token_digest(body.invite_token))
        .first()
    )
    if (
        invite is None
        or invite.used_at is not None
        or (invite.expires_at is not None and invite.expires_at <= now)
        or (invite.email is not None and invite.email != email)
    ):
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=_INVALID_INVITE)

    user = models.User(
        tenant_id=invite.tenant_id,
        email=email,
        password_hash=hash_password(body.password),
        full_name=(body.full_name or "").strip() or None,
        role=invite.role,
    )
    invite.used_at = now
    db.add(user)
    try:
        db.commit()
    except IntegrityError:
        db.rollback()
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="An account with this email already exists.",
        )
    db.refresh(user)

    # Audit under the tenant context (audit_events RLS has no auth bypass).
    stamper.set_tenant(db, user.tenant_id)
    session = _issue_session(db, user=user, request=request)
    db.commit()
    _audit(
        db,
        "auth.signup",
        {"user_id": str(user.id), "email": user.email, "role": user.role, "ip": _client_ip(request)},
        tenant_id=user.tenant_id,
        request=request,
    )
    return session


@router.post("/login")
def login(body: LoginRequest, request: Request, auth_ctx=Depends(auth_flow_session)):
    """Verify email + password (+ captcha) and return a live session."""

    db, stamper = auth_ctx
    _require_captcha(body.captcha_token, request)

    email = normalize_email(body.email)
    now = datetime.now(timezone.utc)
    user = db.query(models.User).filter(models.User.email == email).first()
    if user is None:
        # Uniform cost + error for unknown accounts (no user enumeration).
        dummy_password_verify(verify_password_hash)
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail=_INVALID_CREDENTIALS)

    if user.locked_until is not None and user.locked_until > now:
        raise HTTPException(
            status_code=status.HTTP_429_TOO_MANY_REQUESTS,
            detail="Too many failed sign-in attempts — the account is temporarily locked.",
        )

    if not user.is_active or not verify_password_hash(body.password, user.password_hash):
        user.failed_login_attempts = (user.failed_login_attempts or 0) + 1
        if user.failed_login_attempts >= MAX_FAILED_LOGINS:
            user.locked_until = now + timedelta(minutes=LOCKOUT_MINUTES)
            user.failed_login_attempts = 0
        db.commit()
        stamper.set_tenant(db, user.tenant_id)
        _audit(
            db,
            "auth.login.failure",
            {"user_id": str(user.id), "email": user.email, "ip": _client_ip(request)},
            tenant_id=user.tenant_id,
            request=request,
        )
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail=_INVALID_CREDENTIALS)

    user.failed_login_attempts = 0
    user.locked_until = None
    user.last_login_at = now
    stamper.set_tenant(db, user.tenant_id)
    session = _issue_session(db, user=user, request=request)
    db.commit()
    _audit(
        db,
        "auth.login.success",
        {"user_id": str(user.id), "email": user.email, "ip": _client_ip(request)},
        tenant_id=user.tenant_id,
        request=request,
    )
    return session


@router.post("/refresh")
def refresh(body: RefreshRequest, request: Request, auth_ctx=Depends(auth_flow_session)):
    """Rotate a refresh token and return a fresh session.

    Reuse detection: presenting an already-revoked token means the token was
    copied — the entire family is revoked and the user must sign in again.
    Routine rotations are deliberately NOT audit-logged (a 15-minute access
    TTL would flood the chain); reuse events always are.
    """

    db, stamper = auth_ctx
    now = datetime.now(timezone.utc)
    row = (
        db.query(models.AuthRefreshToken)
        .filter(models.AuthRefreshToken.token_hash == refresh_token_digest(body.refresh_token))
        .first()
    )
    if row is None:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail=_INVALID_CREDENTIALS)

    stamper.set_tenant(db, row.tenant_id)
    if row.revoked_at is not None:
        # Theft: revoke the whole family and make noise in the audit chain.
        (
            db.query(models.AuthRefreshToken)
            .filter(
                models.AuthRefreshToken.family_id == row.family_id,
                models.AuthRefreshToken.revoked_at.is_(None),
            )
            .update({"revoked_at": now}, synchronize_session=False)
        )
        db.commit()
        _audit(
            db,
            "auth.refresh.reuse_detected",
            {
                "user_id": str(row.user_id),
                "family_id": str(row.family_id),
                "ip": _client_ip(request),
                "risk": "high",
            },
            tenant_id=row.tenant_id,
            request=request,
        )
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Session was revoked — please sign in again.",
        )
    if row.expires_at is not None and row.expires_at <= now:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Session expired — please sign in again.",
        )

    user = db.query(models.User).filter(models.User.id == row.user_id).first()
    if user is None or not user.is_active:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail=_INVALID_CREDENTIALS)

    row.revoked_at = now
    session = _issue_session(db, user=user, request=request, family_id=row.family_id)
    db.commit()
    return session


@router.post("/logout", status_code=status.HTTP_204_NO_CONTENT)
def logout(body: LogoutRequest, request: Request, auth_ctx=Depends(auth_flow_session)):
    """Revoke the presented refresh token (idempotent)."""

    db, stamper = auth_ctx
    now = datetime.now(timezone.utc)
    row = (
        db.query(models.AuthRefreshToken)
        .filter(models.AuthRefreshToken.token_hash == refresh_token_digest(body.refresh_token))
        .first()
    )
    if row is not None and row.revoked_at is None:
        row.revoked_at = now
        db.commit()
        stamper.set_tenant(db, row.tenant_id)
        _audit(
            db,
            "auth.logout",
            {"user_id": str(row.user_id), "ip": _client_ip(request)},
            tenant_id=row.tenant_id,
            request=request,
        )
    return None


@router.get("/me")
def me(
    request: Request,
    client: AuthenticatedClient = Depends(require_api_client),
    db: Session = Depends(tenant_scoped_session),
):
    """Profile for the currently authenticated portal user."""

    user_id = getattr(request.state, "user_id", None)
    if user_id is None:
        # Machine-lane (API key) callers have no portal profile.
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="This identity is an API key, not a portal account.",
        )
    user = db.query(models.User).filter(models.User.id == user_id).first()
    if user is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Account not found.")
    return {
        "id": str(user.id),
        "email": user.email,
        "full_name": user.full_name,
        "role": user.role,
        "tenant_id": str(user.tenant_id),
        "last_login_at": user.last_login_at.isoformat() if user.last_login_at else None,
    }


@router.post("/invites", status_code=status.HTTP_201_CREATED)
def create_invite(
    body: InviteRequest,
    request: Request,
    client: AuthenticatedClient = Depends(require_scope("admin")),
    db: Session = Depends(tenant_scoped_session),
):
    """Admin-only: generate a single-use invite for this tenant.

    The raw token is returned ONCE — only its SHA-256 digest is stored.
    """

    if body.role not in KNOWN_ROLES:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=f"role must be one of {sorted(KNOWN_ROLES)}.",
        )
    email = normalize_email(body.email) if body.email else None
    if email:
        _check_email_shape(email)
    raw_token = generate_invite_token()
    invite = models.TenantInvite(
        tenant_id=client.tenant_id,
        email=email,
        token_hash=invite_token_digest(raw_token),
        role=body.role,
        expires_at=datetime.now(timezone.utc)
        + timedelta(hours=settings.BUDDI_INVITE_EXPIRY_HOURS),
        created_by=getattr(request.state, "user_id", None) or client.api_key_id,
    )
    db.add(invite)
    try:
        db.commit()
    except SQLAlchemyError as exc:
        db.rollback()
        logger.error("invite creation failed: %s", exc)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Could not create the invite.",
        )
    _audit(
        db,
        "auth.invite.created",
        {
            "invite_id": str(invite.id),
            "email": invite.email,
            "role": invite.role,
            "created_by": str(invite.created_by) if invite.created_by else None,
        },
        tenant_id=client.tenant_id,
        request=request,
    )
    return {
        "invite_token": raw_token,
        "expires_at": invite.expires_at.isoformat(),
        "role": invite.role,
        "email": invite.email,
    }

