"""user_accounts: portal users, refresh tokens, tenant invites (invite-only auth)

Revision ID: h8i9j0k1l2m3
Revises: g7h8i9j0k1l2
Create Date: 2026-07-23 10:00:00.000000

Adds the human-login data model for the operator portal (email + password +
hCaptcha, invite-only onboarding):

  * ``users`` — one row per portal account. Passwords are Argon2id hashes
    (application-side; the DB never sees plaintext). Account lockout columns
    (``failed_login_attempts`` / ``locked_until``) blunt online brute force.
  * ``auth_refresh_tokens`` — SHA-256 digests of rotating refresh tokens.
    Only digests are stored, so a DB read never yields a usable credential.
    ``family_id`` enables RFC 6819 §5.2.2.3 reuse detection: presenting a
    revoked token revokes the whole family.
  * ``tenant_invites`` — SHA-256 digests of single-use, time-bounded invite
    tokens generated by tenant admins.

Row-level security: all three tables get FORCE RLS with the standard
``app.tenant_id`` isolation policy **plus** an ``app.auth_bypass`` escape
hatch — the mirror image of the ``app.worker_mode`` pattern used for jobs
(``g7h8i9j0k1l2``). Login / signup / refresh must look up credentials
*before* any tenant context exists; those pre-auth routes stamp
``app.auth_bypass='1'`` on their own short-lived session (see
``core/db_session.py:auth_flow_session``). Authenticated routes never stamp
it, so portal routes stay strictly tenant-isolated.
"""

from __future__ import annotations

import logging
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "h8i9j0k1l2m3"
down_revision: Union[str, Sequence[str], None] = "g7h8i9j0k1l2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

logger = logging.getLogger("alembic.user_accounts")

_TABLES = ("users", "auth_refresh_tokens", "tenant_invites")


def _policy_name(table: str) -> str:
    return f"{table}_tenant_or_auth_bypass_isolation"


def _policy_sql() -> str:
    # Standard tenant isolation OR an explicit pre-auth bypass stamped only by
    # the login/signup/refresh routes. Mirrors g7h8i9j0k1l2's worker_mode policy.
    return (
        "current_setting('app.auth_bypass', true) = '1' "
        "OR (current_setting('app.tenant_id', true) IS NOT NULL "
        "AND current_setting('app.tenant_id', true) <> '' "
        "AND tenant_id::text = current_setting('app.tenant_id', true))"
    )


def _has_table(bind, table: str) -> bool:
    return sa.inspect(bind).has_table(table)


def upgrade() -> None:
    bind = op.get_bind()

    # 1. users -----------------------------------------------------------------
    if not _has_table(bind, "users"):
        op.create_table(
            "users",
            sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
            sa.Column("tenant_id", postgresql.UUID(as_uuid=True), nullable=False),
            sa.Column("email", sa.String(320), nullable=False),
            sa.Column("password_hash", sa.Text(), nullable=False),
            sa.Column("full_name", sa.String(255), nullable=True),
            sa.Column("role", sa.String(32), nullable=False, server_default="clinician"),
            sa.Column("is_active", sa.Boolean(), nullable=False, server_default="true"),
            sa.Column("failed_login_attempts", sa.Integer(), nullable=False, server_default="0"),
            sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
            sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
            sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], name="users_tenant_id_fkey"),
            sa.PrimaryKeyConstraint("id", name="users_pkey"),
            sa.UniqueConstraint("email", name="uq_users_email"),
        )
        op.create_index("ix_users_email", "users", ["email"], unique=True)

    # 2. auth_refresh_tokens ---------------------------------------------------
    if not _has_table(bind, "auth_refresh_tokens"):
        op.create_table(
            "auth_refresh_tokens",
            sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
            sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
            sa.Column("tenant_id", postgresql.UUID(as_uuid=True), nullable=False),
            sa.Column("token_hash", sa.String(64), nullable=False),
            sa.Column("family_id", postgresql.UUID(as_uuid=True), nullable=False),
            sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("created_ip", sa.String(64), nullable=True),
            sa.Column("user_agent", sa.String(255), nullable=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
            sa.ForeignKeyConstraint(
                ["user_id"], ["users.id"], name="auth_refresh_tokens_user_id_fkey"
            ),
            sa.ForeignKeyConstraint(
                ["tenant_id"], ["tenants.id"], name="auth_refresh_tokens_tenant_id_fkey"
            ),
            sa.PrimaryKeyConstraint("id", name="auth_refresh_tokens_pkey"),
            sa.UniqueConstraint("token_hash", name="uq_auth_refresh_tokens_token_hash"),
        )
        op.create_index(
            "ix_auth_refresh_tokens_token_hash",
            "auth_refresh_tokens",
            ["token_hash"],
            unique=True,
        )
        op.create_index("ix_auth_refresh_tokens_user_id", "auth_refresh_tokens", ["user_id"])
        op.create_index("ix_auth_refresh_tokens_tenant_id", "auth_refresh_tokens", ["tenant_id"])
        op.create_index("ix_auth_refresh_tokens_family_id", "auth_refresh_tokens", ["family_id"])
        logger.info("created table auth_refresh_tokens")

    # 3. tenant_invites ----------------------------------------------------------
    if not _has_table(bind, "tenant_invites"):
        op.create_table(
            "tenant_invites",
            sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
            sa.Column("tenant_id", postgresql.UUID(as_uuid=True), nullable=False),
            sa.Column("email", sa.String(320), nullable=True),
            sa.Column("token_hash", sa.String(64), nullable=False),
            sa.Column("role", sa.String(32), nullable=False, server_default="clinician"),
            sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("created_by", postgresql.UUID(as_uuid=True), nullable=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
            sa.ForeignKeyConstraint(
                ["tenant_id"], ["tenants.id"], name="tenant_invites_tenant_id_fkey"
            ),
            sa.PrimaryKeyConstraint("id", name="tenant_invites_pkey"),
            sa.UniqueConstraint("token_hash", name="uq_tenant_invites_token_hash"),
        )
        op.create_index(
            "ix_tenant_invites_token_hash", "tenant_invites", ["token_hash"], unique=True
        )
        op.create_index("ix_tenant_invites_tenant_id", "tenant_invites", ["tenant_id"])
        logger.info("created table tenant_invites")

        op.create_index("ix_users_tenant_id", "users", ["tenant_id"])
        logger.info("created table users")

    # 4. RLS ---------------------------------------------------------------------
    for table in _TABLES:
        if not _has_table(bind, table):
            continue
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(f"DROP POLICY IF EXISTS {_policy_name(table)} ON {table}")
        op.execute(
            f"""
            CREATE POLICY {_policy_name(table)}
                ON {table}
                USING ({_policy_sql()})
                WITH CHECK ({_policy_sql()});
            """
        )
        logger.info("RLS enabled on %s", table)


def downgrade() -> None:
    bind = op.get_bind()
    for table in _TABLES:
        if not _has_table(bind, table):
            continue
        op.execute(f"DROP POLICY IF EXISTS {_policy_name(table)} ON {table}")
        op.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")
    for table in reversed(_TABLES):
        if _has_table(bind, table):
            op.drop_table(table)

